---
title: "data_wrangling_ii"
author: "Yunjia Liu"
date: "2024-10-10"
output: github_document
---

```{r setup, include=FALSE}
library(rvest)
library(httr)
library(tidyverse)
```


```{r }
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)


```

Get the pieces that you really need.
```{r}
table_marj = 
  drug_use_html |> 
  html_table() |> 
  first() |>
  slice(-1)  #cleaning the NOTE row (on the top of the whole table)
```

Read in cost of living
```{r ex.1}
cost_html = read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york")
table_cost = 
  cost_html |>
  html_table(header = TRUE) |>
  first()
```

## css selector
how to define the title (how to extract the exact type of data)

```{r}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")

title_vec = 
  swm_html |>
  html_elements(".ipc-title-link-wrapper .ipc-title__text") |>
  html_text()

metascore_vec = 
  swm_html |>
  html_elements(".metacritic-score-box") |>
  html_text()

runtime_vec = 
  swm_html |>
  html_elements(".dli-title-metadata-item:nth-child(2)") |>
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    score = metascore_vec,
    runtime = runtime_vec)

```



Let's import some books

```{r}
url = "http://books.toscrape.com"

books_html = read_html(url)

books_titles = 
  books_html |>
  html_elements("h3") |>
  html_text2()

books_stars = 
  books_html |>
  html_elements(".star-rating") |>
  html_attr("class")

books_price = 
  books_html |>
  html_elements(".price_color") |>
  html_text()

books = tibble(
  title = books_titles,
  stars = books_stars,
  price = books_price
)

```


## Use API

```{r}

nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
  content()

# set a limit the number of rows (instructions given by the website) 
brfss_df = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) |> 
  content()


poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") |>
  content()

poke[["name"]]

poke$height
poke$abiities
```

